### PR TITLE
feat: use babel-preset-proposal-typescript instead of hard coding plugins

### PR DESCRIPTION
**Pull request by JounQin**

### CODE REVIEW

**Comment by wessberg** [comment]
Hi there.
Thanks for your interest in rollup-plugin-ts. I'm glad you want to contribute.

However, I'm not entirely sure I understand what you are trying to achieve with this Pull Request? You didn't provide any details whatsoever, so I can only guess. However, based on your code, it looks like you are trying to add support for compiling Stage <3 features not supported by Typescript via Babel plugins.

Have you read [this section](https://github.com/wessberg/rollup-plugin-ts#when-combined-with-babel-what-does-typescript-do-and-what-does-babel-do) in the README?
The babel plugins and presets only take effect when you configure this plugin with the `transpiler: "babel"` option. When you configure rollup-plugin-ts to use babel, Typescript will still be used for emitting diagnostics and transforming typescript-specific features. In that phase, Typescript still needs to be able to parse the source code, so even though you may add a babel transformer for something like the pipeline operator, as long as Typescript can't parse it, compilation will fail.

If the intention of your Pull Request is to use a preset for shipped proposals rather than using the plugins directly, I'm all for it, but as far as I can tell, https://github.com/rx-ts/babel-preset-proposal-typescript enable a lot of stage 0-2 proposals, and I don't think that should be enabled by default in rollup-plugin-ts.

**Comment by tunnckoCore** [comment]
Agree. Not that needed. Also check out [_"The 5 Big Features of TypeScript 3.7 and How to Use Them"_](https://httptoolkit.tech/blog/5-big-features-of-typescript-3.7/). In short top-level await, null coalescing, optional chaining will be included.

Btw, @wessberg, aside from all that... I was always thinking isn't there a better way to generate types (and type bundles). Why I think that such place can be the Babel typescript transform plugin? Instead of just removing them...

I may guess it's because the auto type inferencing? Which you won't get access to when we are in Babel transform plugin context.

**Comment by JounQin** [comment]
Sorry to misunderstand the purchase of integration of babel for this plugin. I was thinking a workflow like `sourcecode -> babel-preset-proposal-typescript- TypeScript -> other babel transpiles`, so we can use most modern features in TypeScript with babel. Additionally, maybe I should implement it with something like [ttypscript](https://github.com/cevek/ttypescript).

What do think about my proposal?

**Comment by tunnckoCore** [comment]
Sounds good. I always thought for such thing.

**Comment by wessberg** [comment]
I've thought of a similar thing in the past, but there are two things that currently make it unfeasible:

First, in order for it to work properly, it would require the initial Babel step to go from Typescript => Typescript. Meaning, it would need to preserve all type information and other Typescript-specific constructs such as interfaces, type literals and const enums after the Babel step.

For example, the optional chaining Babel plugin would need to be able to parse Typescript-specifics intermixed with the new proposed syntax (for example `(foo as any)?.bar`. Even if coupled with something like the `babel-preset-typescript` preset, you would get JavaScript back from Babel. And we still need the Typescript specific parts because of [this](https://github.com/wessberg/rollup-plugin-ts/blob/master/README.md#okay-then-why-wouldnt-you-use-just-babel). Theoretically, these things could instead be built with Typescript Custom Transformers (this plugin itself leverages several of such transformers), but unfortunately, Custom Transformers run during the emit-phase which is _after_ Typescript generates diagnostics, and those would consider the experimental features as syntactical errors.

The other thing is that an important goal for me is that there's correlation between what the Typescript language service in your code editor of choice says, and what you get back from running a build-step. And since there's currently no way of performing code transformations prior to the phase where Typescript generates diagnostics, you would have all sorts of errors popping in your editor.

**Comment by JounQin** [comment]
> Sounds good. I always thought for such thing.
> 
> We can make the following, which will be one more cool future of this plugin:
> 
> ```
> source > babel stage < 3 transforms (only) > transpiler: typescript | babel
> ```
> 
> Yup. Pretty cool. So, babel before and after the typescript job. :D
> 
> But anyway, I think it's possible currently to pass the babel plugin two times. Cuz `ttypscript` is more hackier and unnecessary approach to me;
> 
> ```js
> {
>   plugins: [
>     babel({ babelrc: false, stage0to3 })
>     anyTypescriptPlugin()
>     babel(/* auto pickup babel config */)
>   ]
> }
> ```
> 
> Sooo... yea, lets not put it here. It's enough codebase here anyway.

@tunnckoCore It seems good to me, does it work as expected for now?

@wessberg `babel-preset-typescript` will erase the type infos but `babel-preset-proposal-typescript` will not.

So it should work as @tunnckoCore suggested:

```js
{
  plugins: [
    babel({ babelrc: false, presets: 'proposal-typescript' })
    anyTypescriptPlugin()
    babel(/* auto pickup babel config */)
  ]
}
```

**Comment by wessberg** [comment]
@JounQin, huh, interesting that Babel can go from Typescript => Typescript. I am open to adding an additional configuration option that takes some Babel options (or a path to a Babel config file) that should be used for transforming the source code prior to it being added to a Typescript program as a SourceFile. That could work.

It will still be shown as syntax errors in your editor since the language service wouldn't support it, but I'm open to adding a preprocessing hook like that.

However, enabling the stage 0-2 features that isn't supported by Typescript by default is not something I think we should do.

**Comment by JounQin** [comment]
Maybe we should just notice about this usage in document, manually prepend `babel` plugin with `babelrc: false` is just so simple.

I will close this PR which is far away from the discussion then.

**Comment by JounQin** [comment]
@wessberg Last thing to confirm, will the language service of this plugin continue work in this case?

**Comment by tunnckoCore** [comment]
@wessberg oooh yea yea. I completely forgot about that. My proposal won't work.

> @JounQin: Maybe we should just notice about this usage in document, manually prepend babel plugin with babelrc: false is just so simple.

This won't work, at all. First, because we don't have plugins like "strip typescript types" and then "add types". And even if we had, the second problem with editors remain.

> although it would be great if we can handle with babel processed code content, but report error according to original source map.

Sounds good if possible.

**Comment by JounQin** [comment]
> This won't work, at all. First, because we don't have plugins like "strip typescript types" and then "add types".

@tunnckoCore You might didn't notice my comment above about `babel-preset-proposal-typescript`. We don't need to add types back, because they're not even been removed by `babel` + `babel-preset-proposal-typescript` which only enables `plugin-syntax-typescript` without `transforming` it.

**Comment by tunnckoCore** [comment]
No, I noticed it, haha. But... Uh oh, yea. Then it would be cool to fix the other remaining editor problem somehow.

**Pull request closed without merging**
