### PR TITLE
chore: rename `@wessberg/rollup-plugin-ts` to unscoped `rollup-plugin-ts`

### PR DESCRIPTION
**Pull request by JounQin**
How do you think?

### CODE REVIEW

**Comment by wessberg** [comment]
I've been going back and forth over this issue in my head for months. Frankly, I'm in doubt. I generally don't like unscoped packages and it's interesting to see how things like the Github package repository won't support it either. It was only after an unscoped version of this library was published on NPM that I had to figure out what to do about it. I'm probably more inclined to deprecate the unscoped version than the other way around. But I'd like to collect feedback on this matter before making any decisions.

**Comment by JounQin** [comment]
`@wessberg` is a personal prefix which makes me -1 to this, `@rollup/plugin-ts` would be best, but for now this project is not an official `rollup` plugin, so I think `rollup-plugin-ts` would be much clearer.

**Comment by wessberg** [comment]
The point about the Github Package Registry weights strongly in my mind. If I want to move `rollup-plugin-ts` to the Github Package Registry or support it there as well, it will need to be scoped to a user or an organization, in this case me. All other packages in the ecosystem, including the most popular ones, will face the same challenge should they decide to do the same.

I generally tend to use scoped packages for _everything_. I understand your point about `@wessberg` sounding like a personal prefix, but really I just see packages as simply following the form `<author><package>` to avoid global namespacing which is generally considered a bad thing. I understand how you can see it differently, like: `<project><subpackage>`, and that form works great for things like `@angular/<subpackage>`, `@rollup/plugin-*` et cetera, but for other scenarios like this where the package stands on its own, I _still_ prefer scoped package names.

Now the reason why I'm in doubt still is that I know that the JavaScript ecosystem in 2020 still really loves global package names. I've seen popular packages go as far as drop their scopes to make their packages feel more "official" or make them easier to install. I understand all of this. What I'm saying is that I'm in doubt and still haven't heard any convincing counter-arguments. So I'm looking to collect more feedback.

I'll keep this PR open as we continue the discussion.

**Comment by JounQin** [comment]
@wessberg As you describe at https://github.com/rx-ts/rollup-plugin-ts/issues/2 and discussions through #57

>  I do think that may lead to confusion as to what's the original package, and what's the fork.

It is clear that `rollup-plugin-ts` is better to understand than `@wessberg/rollup-plugin-ts` for all other users.

**Comment by wessberg** [comment]
I respect your opinion, but I've already described in great detail why I prefer scoping my packages. As I said, for the time being I'm more inclined to deprecate the non-scoped than the scoped version of the package. I don't agree that it is "better" or easier to understand without a scope, but I do understand why you might think that, especially because scoping is still relatively new in the NPM ecosystem.

Anyway, I decided to [make a Twitter poll](https://twitter.com/FredWessberg/status/1223243536830693377) to find out where people stand on this issue in general and it turned out to be 50/50 (however I only got 6 responses, so it's not really saying much 🙂)

**Comment by benmccann** [comment]
I don't have an opinion one way or the other except to say that if you go with a scoped version you might consider changing the scope to something like `@rollup-ts` to make it seem more like a community-maintained plugin that's a bit more official and open to community contributions, etc.

**Comment by wessberg** [comment]
Hi @JounQin,

I've recently decided to drop the `@wessberg` scope from most of my libraries, since this has been a request I've seen multiple times across multiple packages. Because of that, I've changed my stance on this issue. However, since your PR is pretty old and has diverged quite a bit from master, I've closed your PR and instead implemented the change myself.

**Pull request closed without merging**
